### ISSUE TITLE
UnsatisfiedLinkError:  Error looking up function 'strlen'

### ISSUE THREAD

**Issue by bhelx** [extism/java-sdk#21]
A report from a user. They got this error when trying to load a plugin but it failed:

```
at com.sun.jna.Function.<init> (Function.java:252)
    at com.sun.jna.NativeLibrary.getFunction (NativeLibrary.java:604)
    at com.sun.jna.NativeLibrary.getFunction (NativeLibrary.java:580)
    at com.sun.jna.NativeLibrary.getFunction (NativeLibrary.java:566)
    at com.sun.jna.Library$Handler.invoke (Library.java:243)
    at jdk.proxy3.$Proxy28.strlen (Unknown Source)
    at org.extism.sdk.Plugin.<init> (Plugin.java:49)
    at org.extism.sdk.Plugin.<init> (Plugin.java:61)
    at org.spirefy.engine.PluginEngine.load (PluginEngine.java:28)
    at org.spirefy.example.Example.main (Example.java:12)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:254)
    at java.lang.Thread.run (Thread.java:1570)
java.lang.UnsatisfiedLinkError: Error looking up function 'strlen': The specified procedure could not be found.
 ```
 
 
Looks to me like this code is not correct: https://github.com/extism/java-sdk/blob/91c19490d2d492566ba67fd223220d5ff35b6d64/src/main/java/org/extism/sdk/Plugin.java#L49

we don't expose have a `strlen` function in libextism.

**Comment by apisorbust** [comment]
I am puzzled by this. The example URL code works fine from Java host. But trying to load a local wasm module it seems like it isn't even getting to my module.. e.g. the extism.sdk.Plugin.init call is looking for that strlen func for some reason? Which is odd that it would be since there is a length function in Java anyway. I feel like this is one of those "oh.. it's this other thing unrelated that is somehow causing this issue to rear up".

**Comment by apisorbust** [comment]
Just another thought on this.. it seems like the strlen() call is because the p is null (prior to it in the Plugin.java call). So my assumption is p being null means it did not find/load my plugin.. The code: 

`        Pointer p = LibExtism.INSTANCE.extism_plugin_new(manifestBytes, manifestBytes.length,
                ptrArr,
                functions == null ? 0 : functions.length,
                withWASI,
                errormsg);
        if (p == null) {
            if (functions != null)
                for (int i = 0; i < functions.length; i++) {
                   LibExtism.INSTANCE.extism_function_free(functions[i].pointer);
                }
            int errlen = LibExtism.INSTANCE.strlen(errormsg[0]);
            byte[] msg = new byte[errlen];
            errormsg[0].read(0, msg, 0, errlen);
            LibExtism.INSTANCE.extism_plugin_new_error_free(errormsg[0]);
            throw new ExtismException(new String(msg));
        }`

I assume above that Pointer P using LibExtism.INSTNACE.extism_plugin_new() is trying to load/create the plugin, but that it returns null and this the if (p == null) bit runs, which is where this strlen function not found is happening.

I'd be interested if whoever owns/knows the code might explain the issue with INSTANCE.strlen().

**Comment by bhelx** [comment]
I think perhaps @thomasdarimont or @Zwiterrion may have written that piece. I believe it's a mistake maybe the testing plugin had that export but it's not part of Extism. I think we should remove it and instead use extism_plugin_error: https://github.com/extism/java-sdk/blob/91c19490d2d492566ba67fd223220d5ff35b6d64/src/main/java/org/extism/sdk/LibExtism.java#L108

Also perhaps @zshipko has an idea of the correct behavior here.

**Comment by bhelx** [comment]
I'd be happy to fix it but I can't reproduce the problem yet.

**Comment by thomasdarimont** [comment]
@bhelx I'll take a look now.

**Comment by thomasdarimont** [comment]
I cannot reproduce the problem either, as the code is correctly executed.
![image](https://github.com/extism/java-sdk/assets/314690/25cbb76f-9855-410d-84c7-a1a7b38ef874)

The strlen function is exposed by the glibc 
```
$ readelf -Ws --dyn-syms /usr/local/lib/libextism.so | grep strlen
    53: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND strlen@GLIBC_2.2.5 (3)
 43603: 0000000000000000     0 FUNC    GLOBAL DEFAULT  UND strlen@@GLIBC_2.2.5
```

**Comment by Zwiterrion** [comment]
I just check on arm64, and i got the `strlen` function. 

@apisorbust can you give us your os ? You may be on windows and we tested on Mac and Linux

**Comment by bhelx** [comment]
> The strlen function is exposed by the glibc

Ohhh I see. Yeah, we can't assume that is there. We should be able to not rely on it. Idk what OS he was on, he didn't say, but his paths suggested windows

**Comment by thomasdarimont** [comment]
@bhelx I found a way to get rid of the strlen function... see #22

**Comment by apisorbust** [comment]
Sorry.. didn't see this update thread. Yah.. windows 64.. but ya'll figured it out already. Just waiting on maven push for my app to pull down the fix and get cracking. Thank you again for jumping in on this and fixing it.
